### ISSUE TITLE
Startup only shows white screen

### ISSUE THREAD

**Issue by piman51277** [gt-cs2110/lc3tools#28]
System: Debian 12
Kernel: 6.1.0-25amd
DE: KDE Plasma 5.27.5

As title. Starting LC3Tools using Appimage starts the app, but it only shows an initial grey screen before turning white.
Once the screen turns white, the toolbar appears and is functional.

Logs:
```
[12:37:50.387] [info] Checking for update
[12:37:50.974] [info] Update for version 3.1.0 is not available (latest version: 3.1.0, downgrade is disallowed).
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

**Comment by Yanderuri** [comment]
Yoooo Linux user spotted.

On a serious note, we haven't rebuilt the linux appimage for awhile and I'm like the only TA that uses linux.
If you would like to compile a new version, check out https://github.com/endorpersand/lc3tools

Hopefully we can build the flatpak soon

**Comment by endorpersand** [comment]
Update complete: [v4.0.1](https://github.com/gt-cs2110/lc3tools/releases/tag/v4.0.1)

`.flatpak` and `.zip` installs are present there. I do not know enough about Linux to be sure that they work, but they're there now. AppImage unfortunately will not be created because it is not officially supported by Electron Forge.

Theoretically, we could make `.deb` and `.rpm` installs, but I am trying to minimize the number of installs we have to manage and we already have enough trouble with managing the few Linux builds we already have, so I'm going to avoid doing that unless there is an absolute need to do so.
